server:
  port: 8000

spring:
  profiles:
    active: dev

---

spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

---

#spring:
#  profiles: dev
#  data.mongodb.uri: mongodb+srv://sebastianzapata82192:sebastianzapata82192@cluster0.3ldzt6j.mongodb.net/?retryWrites=true&w=majority
#  data.mongodb.database: amazonecommerce


spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/taller2
    username: root
    password: ejemplo123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true